### ISSUE TITLE
'numpy.ndarray' object has no attribute 'numpy'.

### ISSUE THREAD

**Issue by jrsacher** [waylandy/phosformer#1]
I tried to submit this to the repository linked in your publication, but, apparently, I can't!

I received this error while running predictions:
```
Traceback (most recent call last):
  File "/Users/joshuasacher/phosformer/wip1_S234.py", line 17, in <module>
    predictions = Phosformer.predict_many(
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joshuasacher/phosformer/Phosformer/modules.py", line 204, in predict_many
    return np.array([i['pred'] for i in batch_job(kinases, peptides, **kwargs)])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joshuasacher/phosformer/Phosformer/modules.py", line 204, in <listcomp>
    return np.array([i['pred'] for i in batch_job(kinases, peptides, **kwargs)])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joshuasacher/phosformer/Phosformer/modules.py", line 96, in batch_job
    pred = softmax(result['logits'].cpu(), axis=1)[:,1].numpy()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'numpy.ndarray' object has no attribute 'numpy'. Did you mean: 'dump'?
```
It look like, on [line 96](https://github.com/waylandy/phosformer/blob/6e7c019ba5a4c4f6cf7e44c5359c6115afc14c16/Phosformer/modules.py#L96) of `modules.py`, the `.numpy()` is unnecessary, as `softmax` already returns a numpy array. After deleting `.numpy()`, the code ran fine.

I figured this wasn't worth a pull request since the (likely) fix is so simple.

Cheers,

Josh

**Comment by Sreejith915** [comment]
This was helpful ! 
Thank You !
Sree
